### ISSUE TITLE
Kanban Setup

### ISSUE THREAD

**Issue by initseis** [initseis/javascript-capstonee#1]
https://github.com/sevinchek/capstone-kanban

We are two collaborators in this group:
@EroAuditore - Student A
@sevinchek - Student B

**Comment by carlos-ssh** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
